// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class LearnBoar
{
  static readonly string __ServiceName = "LearnBoar";

  static readonly grpc::Marshaller<global::EnvData> __Marshaller_EnvData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EnvData.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::Action> __Marshaller_Action = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Action.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::AgentData> __Marshaller_AgentData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AgentData.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::AgentId> __Marshaller_AgentId = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AgentId.Parser.ParseFrom);

  static readonly grpc::Method<global::EnvData, global::Action> __Method_SendData = new grpc::Method<global::EnvData, global::Action>(
      grpc::MethodType.Unary,
      __ServiceName,
      "SendData",
      __Marshaller_EnvData,
      __Marshaller_Action);

  static readonly grpc::Method<global::AgentData, global::AgentId> __Method_CreateAgent = new grpc::Method<global::AgentData, global::AgentId>(
      grpc::MethodType.Unary,
      __ServiceName,
      "CreateAgent",
      __Marshaller_AgentData,
      __Marshaller_AgentId);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::DataReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of LearnBoar</summary>
  [grpc::BindServiceMethod(typeof(LearnBoar), "BindService")]
  public abstract partial class LearnBoarBase
  {
    public virtual global::System.Threading.Tasks.Task<global::Action> SendData(global::EnvData request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::AgentId> CreateAgent(global::AgentData request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for LearnBoar</summary>
  public partial class LearnBoarClient : grpc::ClientBase<LearnBoarClient>
  {
    /// <summary>Creates a new client for LearnBoar</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public LearnBoarClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for LearnBoar that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public LearnBoarClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected LearnBoarClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected LearnBoarClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::Action SendData(global::EnvData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return SendData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Action SendData(global::EnvData request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_SendData, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Action> SendDataAsync(global::EnvData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return SendDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Action> SendDataAsync(global::EnvData request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_SendData, null, options, request);
    }
    public virtual global::AgentId CreateAgent(global::AgentData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return CreateAgent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::AgentId CreateAgent(global::AgentData request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_CreateAgent, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::AgentId> CreateAgentAsync(global::AgentData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return CreateAgentAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::AgentId> CreateAgentAsync(global::AgentData request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_CreateAgent, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override LearnBoarClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new LearnBoarClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(LearnBoarBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_SendData, serviceImpl.SendData)
        .AddMethod(__Method_CreateAgent, serviceImpl.CreateAgent).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, LearnBoarBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_SendData, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EnvData, global::Action>(serviceImpl.SendData));
    serviceBinder.AddMethod(__Method_CreateAgent, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AgentData, global::AgentId>(serviceImpl.CreateAgent));
  }

}
#endregion
